// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOooavw_VAcqgfCdYN0CPrs84B1Qo-WM',
    appId: '1:516654462376:web:fc92d1ea91cf8503eb599d',
    messagingSenderId: '516654462376',
    projectId: 'flutter-login-app-7ce42',
    authDomain: 'flutter-login-app-7ce42.firebaseapp.com',
    storageBucket: 'flutter-login-app-7ce42.appspot.com',
    measurementId: 'G-1GNBMH5PTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmdVK1uS3RLni-CMp_hzdo-iFHlw53iQ',
    appId: '1:516654462376:android:33e9ac9d5022a802eb599d',
    messagingSenderId: '516654462376',
    projectId: 'flutter-login-app-7ce42',
    storageBucket: 'flutter-login-app-7ce42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTW9VK7w4Ght_jOyHquXT5uKLxepPjws',
    appId: '1:516654462376:ios:48d8821f67e5a895eb599d',
    messagingSenderId: '516654462376',
    projectId: 'flutter-login-app-7ce42',
    storageBucket: 'flutter-login-app-7ce42.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTW9VK7w4Ght_jOyHquXT5uKLxepPjws',
    appId: '1:516654462376:ios:42a532c772cb8a99eb599d',
    messagingSenderId: '516654462376',
    projectId: 'flutter-login-app-7ce42',
    storageBucket: 'flutter-login-app-7ce42.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
